apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: heartpoints-org
  name: heartpoints-org
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heartpoints-org
      name: heartpoints-org
    spec:
      containers:
        - name: heartpoints-org
          image: "$(heartpoints_dockerImageTag)"
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: heartpoints-org
spec:
  type: NodePort
  ports:
  - port: 30000
    nodePort: 30000
    targetPort: 5001
  selector:
    app: heartpoints-org
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: 80
  selector:
    app: kubernetes-dashboard