version: 2
jobs:
  onPullRequest:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: herokuApiKey=$herokuApiKey ./heartpoints.sh onPullRequest
  onMasterMerge:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: ./heartpoints.sh onMasterMerge
workflows:
  version: 2
  pipeline:
    jobs:
      - onPullRequest:
          filters:
            branches:
              ignore: master
      - onMasterMerge:
          filters:
            branches:
              only: master